# Generated by Django 2.2.19 on 2022-08-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_post',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_post',
            new_name='text',
        ),
    ]
