# Generated by Django 2.2.19 on 2022-08-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220809_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post',
        ),
    ]
