# Generated by Django 2.2.19 on 2022-08-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220809_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='text_post',
        ),
    ]
