# Generated by Django 2.2.19 on 2022-08-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220809_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_post',
        ),
    ]
