# Generated by Django 2.2.19 on 2022-08-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220809_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_post',
            new_name='AUTHOR',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='DATE_PUBLISHED',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_post',
            new_name='TEXT',
        ),
    ]
