# Generated by Django 2.2.19 on 2022-08-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220809_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='AUTHOR',
            new_name='author_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='DATE_PUBLISHED',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='TEXT',
            new_name='text_post',
        ),
    ]
