# Generated by Django 2.2.19 on 2022-08-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220809_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_post',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_post',
            new_name='text',
        ),
    ]
